// TODO: Remove
// Material Action Types
export const CREATE_MATERIAL_FOLDER = 'CREATE_MATERIAL_FOLDER';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const DELETE_MATERIAL_FOLDER = 'DELETE_MATERIAL_FOLDER';
export const FETCH_MATERIAL_INDEX = 'FETCH_MATERIAL_INDEX';
export const UPDATE_MATERIAL_DIRECTORY_TREE = 'UPDATE_MATERIAL_DIRECTORY_TREE';
export const UPDATE_MATERIAL_INDEX = 'UPDATE_MATERIAL_INDEX';
export const UPLOAD_MATERIAL = 'UPLOAD_MATERIAL';

// game Dev Action Types
export const FETCH_TEST_STORIES = 'FETCH_TEST_STORIES';
export const SAVE_USER_STATE = 'SAVE_USER_STATE';
export const SET_GAME_STATE = 'SET_GAME_STATE';

// GroundControl Action Types
export const CHANGE_DATE_ASSESSMENT = 'CHANGE_DATE_ASSESSMENT';
export const DELETE_ASSESSMENT = 'DELETE_ASSESSMENT';
export const PUBLISH_ASSESSMENT = 'PUBLISH_ASSESSMENT';
export const UPLOAD_ASSESSMENT = 'UPLOAD_ASSESSMENT';
