// game Dev Action Types
export const FETCH_TEST_STORIES = 'FETCH_TEST_STORIES';
export const SAVE_USER_STATE = 'SAVE_USER_STATE';
export const SET_GAME_STATE = 'SET_GAME_STATE';

// GroundControl Action Types
export const CHANGE_DATE_ASSESSMENT = 'CHANGE_DATE_ASSESSMENT';
export const DELETE_ASSESSMENT = 'DELETE_ASSESSMENT';
export const PUBLISH_ASSESSMENT = 'PUBLISH_ASSESSMENT';
export const UPLOAD_ASSESSMENT = 'UPLOAD_ASSESSMENT';
