export const INIT_INVITE = 'INIT_INVITE';
export const INVALID_EDITOR_SESSION_ID = 'INVALID_EDITOR_SESSION_ID';
export const FINISH_INVITE = 'FINISH_INVITE';
export const SET_EDITOR_SESSION_ID = 'SET_EDITOR_SESSION_ID';
export const SET_WEBSOCKET_STATUS = 'SET_WEBSOCKET_STATUS';

export enum XMLHttpReadyState {
  UNSENT = 0,
  OPENED = 1,
  HEADERS_RECEIVED = 2,
  LOADING = 3,
  DONE = 4
}

export enum XMLHttpStatus {
  OK = 200,
  PAGE_NOT_FOUND = 404
}
