approvedGitRepositories:
  - 'https://github.com/source-academy/*'

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 4320 # 3 days

# exempt our own first-party packages
npmPreapprovedPackages:
  - js-slang
  - '@sourceacademy/web-cse-machine'
  - '@sourceacademy/conductor'
