import { expectSaga } from 'redux-saga-test-plan';
import * as actions from '../../actions';
import * as actionTypes from '../../actions/actionTypes';
import { defaultState } from '../../reducers/states';
import playgroundSaga from '../playground';

test('Playground puts changeQueryString action upon taking GENERATE_LZ_STRING', () => {
  return (
    expectSaga(playgroundSaga)
      .withState(defaultState)
      // The default query string generated by defaultState is undefined.
      .put(actions.changeQueryString(undefined))
      .dispatch({
        type: actionTypes.GENERATE_LZ_STRING
      })
      .silentRun()
  );
});
