export const GITHUB_OPEN_FILE = 'GITHUB_OPEN_FILE';
export const GITHUB_SAVE_FILE = 'GITHUB_SAVE_FILE';
export const GITHUB_SAVE_FILE_AS = 'GITHUB_SAVE_FILE_AS';

export const GITHUB_OPEN_FILE_TO_EDITOR = 'GITHUB_OPEN_FILE_TO_EDITOR';

export type GitHubState = 'LOGGED_IN' | 'LOGGED_OUT';
