export const GITHUB_BEGIN_OPEN_DIALOG = 'GITHUB_BEGIN_OPEN_DIALOG';
export const GITHUB_BEGIN_SAVE_AS_DIALOG = 'GITHUB_BEGIN_SAVE_AS_DIALOG';
export const GITHUB_BEGIN_SAVE_DIALOG = 'GITHUB_BEGIN_SAVE_DIALOG';
export const GITHUB_CLOSE_FILE_EXPLORER_DIALOG = 'GITHUB_CLOSE_FILE_EXPLORER_DIALOG';

export const GITHUB_BEGIN_CONFIRMATION_DIALOG = 'GITHUB_BEGIN_CONFIRMATION_DIALOG';
export const GITHUB_CONFIRM_OPEN = 'GITHUB_CONFIRM_OPEN';
export const GITHUB_CONFIRM_OVERWRITING_SAVE = 'GITHUB_CONFIRM_OVERWRITING_SAVE';
export const GITHUB_CONFIRM_CREATING_SAVE = 'GITHUB_CONFIRM_CREATING_SAVE';
export const GITHUB_CANCEL_CONFIRMATION_DIALOG = 'GITHUB_CANCEL_CONFIRMATION_DIALOG';

export type GitHubState = 'LOGGED_IN' | 'LOGGED_OUT';
