module.exports = {
  screenWidth: 1920,
  screenHeight: 1080,
  dialogBoxHeight: 260,
  dialogBoxWidth: 1720,
  dialogBoxPadding: 25,
  fontSize: 44,
  innerDialogPadding: 46,
  avatarOffset: 46,
  nameBoxXPadding: 50,
  nameBoxHeight: 80,
  playerAvatarSize: 300,
  playerAvatarLineWidth: 10,
  playerAvatarOffset: 40,
  glowDistance: 30,
  textSpeed: 0.02,
  localStoryXMLPath: LOCAL_HOST + 'stories/',
  globalStoryXMLPath: ASSETS_HOST + 'stories/',
  locationPath: ASSETS_HOST + 'locations/',
  objectPath: ASSETS_HOST + 'objects/',
  imgPath: ASSETS_HOST + 'images/',
  avatarPath: ASSETS_HOST + 'avatars/',
  uiPath: ASSETS_HOST + 'UI/',
  soundPath: ASSETS_HOST + 'sounds/',
  fadeTime: 0.3,
  nullFunction: function() {}
};
