export const CHANGE_DATE_ASSESSMENT = 'CHANGE_DATE_ASSESSMENT';
export const CHANGE_TEAM_SIZE_ASSESSMENT = 'CHANGE_TEAM_SIZE_ASSESSMENT';
export const DELETE_ASSESSMENT = 'DELETE_ASSESSMENT';
export const PUBLISH_ASSESSMENT = 'PUBLISH_ASSESSMENT';
export const PUBLISH_GRADING_ALL = 'PUBLISH_GRADING_ALL';
export const UNPUBLISH_GRADING_ALL = 'UNPUBLISH_GRADING_ALL';
export const UPLOAD_ASSESSMENT = 'UPLOAD_ASSESSMENT';
export const CONFIGURE_ASSESSMENT = 'CONFIGURE_ASSESSMENT';
